// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2018,2021 IBM Corp.
// Copyright (C) 2021, Oracle and/or its affiliates.

/* For program_invocation_short_name */
#define _GNU_SOURCE

#include <errno.h>
#include <argp.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "cmd.h"
#include "config.h"
#include "compiler.h"
#include "log.h"
#include "version.h"
#include "ahb.h"
#include "host.h"

#include "ccan/autodata/autodata.h"

/* Credits to Ben Klemens for this macro */
#define Sasprintf(write_to, ...) do { \
    char *tmp_string_for_extend = write_to; \
    if (asprintf(&(write_to), __VA_ARGS__) == -1) { \
        write_to = NULL; \
    } \
    free(tmp_string_for_extend); \
} while (0)

const char *argp_program_version = "culvert " CULVERT_VERSION;
const char *argp_program_bug_address = "GitHub amboar/culvert";
/**
 * The root docs will be partially autogenerated from the list of commands
 * available in the cmds array.
 */
char *root_doc = NULL;
static char root_doc_header[] =
    "\n"
    "Culvert -- A Test and Debug Tool for BMC AHB Interfaces"
    "\v"
    "Supported commands:\n";

static struct argp_option root_options[] = {
    { "verbose", 'v', 0, 0, "Get verbose output", 0 },
    { "quiet", 'q', 0, 0, "Don't produce any output", 0 },
    { "skip-bridge", 's', "BRIDGE", 0, "Skip BRIDGE driver", 0 },
    { "list-bridges", 'l', 0, 0, "List available bridge drivers", 0 },
    {0}
};

struct root_arguments {
    char *args[32];
};

static error_t
root_parse_opt(int key, char *arg, struct argp_state *state)
{
    struct root_arguments *arguments = state->input;

    switch (key) {
        case 'q':
            log_set_level(level_none);
            break;
        case 'v':
            log_set_level(level_trace);
            break;
        case 's':
            if (disable_bridge_driver(arg))
                argp_error(state, "Error: '%s' not a recognized bridge name (use '-l' to list)", arg);
            break;
        case 'l':
            print_bridge_drivers();
            break;
        case ARGP_KEY_ARGS:
            /**
             * Any arguments that are not options will be stored in the
             * arguments struct. We will use this to match the command
             * and its arguments.
             */
            for (int i = 0; i < state->argc - state->next; i++)
                arguments->args[i] = state->argv[state->next + i];
            break;
        case ARGP_KEY_END:
            if (state->arg_num < 1)
                argp_usage(state);
            break;
        default:
            return ARGP_ERR_UNKNOWN;
    }

    return 0;
}

static struct argp root_argp = {
    root_options,
    root_parse_opt,
    "<cmd> [CMD_OPTIONS]...",
    NULL, // docs will be set later
    NULL,
    NULL,
    NULL
};

int main(int argc, char *argv[])
{
    struct root_arguments arguments = {0};
    struct cmd **cmds;
    size_t n_cmds = 0;

    /**
     * Always initialise the log level and set a
     * different level if an argument is passed.
     */
    log_set_level(level_info);

    /* Initialise the cmds from autodata. */
    cmds = autodata_get(cmds, &n_cmds);

    /* Sort the commands */
    qsort(cmds, n_cmds, sizeof(void *), cmd_cmp);

    /**
     * Add the short command docs to the root level docs.
     * In case n_cmds is still 0, we will add a note to the help.
     */
    Sasprintf(root_doc, "%s", root_doc_header);
    if (n_cmds == 0)
        Sasprintf(root_doc, "%s  No commands available\n", root_doc);

    for (size_t i = 0; i < n_cmds; i++) {
        struct cmd *cmd = cmds[i];
        Sasprintf(root_doc, "%s  %-15s  %s\n", root_doc, cmd->name, cmd->short_doc);
    }
    root_argp.doc = root_doc;

    /**
     * Parse command-line arguments
     * NOTE: `ARGP_IN_ORDER` is required to make sub-commands work
     * properly and to enforce options to be in order.
    */
    if (argp_parse(&root_argp, argc, argv, ARGP_IN_ORDER, 0, &arguments) != 0) {
        fprintf(stderr, "Error parsing arguments\n");
        goto cleanup_cmds;
    }

    /**
     * Smash the first two arguments together because argp will not automatically
     * add program_invocation_short_name to the arguments.
     */
    char *old_args0 = arguments.args[0];
    arguments.args[0] = malloc(strlen(program_invocation_short_name) + strlen(old_args0) + 1);
    if (!arguments.args[0])
        argp_failure(NULL, 1, ENOMEM, 0);

    sprintf(arguments.args[0], "%s %s", program_invocation_short_name, old_args0);

    for (size_t i = 0; i < n_cmds; i++) {
        struct cmd *cmd = cmds[i];

        if (cmd->parent == NULL && !strcmp(cmd->name, arguments.args[0])) {
            // Top-level command
            exit(cmd->fn(NULL) ? EXIT_FAILURE : EXIT_SUCCESS);
        } else if (cmd->parent != NULL && !strcmp(cmd->parent, arguments.args[0]) && !strcmp(cmd->name, arguments.args[1])) {
            // Sub-command
            int argc = argc - 1;
            char **argv = &argv[1];
            argv[0] = malloc(strlen(arguments.args[0]) + strlen(arguments.args[1]) + 2);
            if (!argv[0])
                argp_failure(NULL, 1, ENOMEM, 0);

            sprintf(argv[0], "%s %s", arguments.args[0], arguments.args[1]);
            exit(cmd->fn(NULL) ? EXIT_FAILURE : EXIT_SUCCESS);
        }
    }

/*
            /**
             * The first argument is the command name, the rest are the
             * arguments for the command.
            for (int i = 0; i < state->argc - state->next; i++)
                arguments->args[i] = state->argv[state->next + i];

            for (size_t i = 0; i < arguments->n_cmds; i++) {
                struct cmd *cmd = arguments->cmds[i];
                if (!strcmp(cmd->name, arguments->args[0])) {
                    // Remove arguments->args[0] from the list
                    for (int j = 0; j < state->argc - state->next; j++)
                        state->argv[state->next + j] = state->argv[state->next + j + 1];
                    state->argc--;

                    if (cmd->parent) {
                        int argc = state->argc - state->next + 1;
                        char **argv = &state->argv[state->next - 1];

                        argv[0] = malloc(strlen(state->name) + strlen(cmd->name) + 2);
                        if (!argv[0])
                            argp_failure(state, 1, ENOMEM, 0);

                        sprintf(argv[0], "%s %s", state->name, cmd->name);

                        argp_parse(cmd->parent, argc, argv, ARGP_IN_ORDER, 0, arguments);
                    } else
                        exit(cmd->fn(state) ? EXIT_FAILURE : EXIT_SUCCESS);
                } else if (!strcmp(cmd->name, arguments->args[1])) {

                }
            }
            */

cleanup_cmds:
    autodata_free(cmds);
    free(root_doc);
    exit(EXIT_FAILURE);
}
